language: python

python: 
 - "3.7"

install:
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls
 - python setup.py install 

script: 
 - pytest --cov=sysmor tests/
after_success:
 - coveralls

